# Generated by Django 5.1.7 on 2025-03-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetting',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
